### ISSUE TITLE
Resume uploading coverage data to Coveralls

### ISSUE THREAD

**Issue by kconner** [willowtreeapps/PinkyPromise#60]
fa20810e64d10829c6d517cf3cb04dcce78f241d removes Slather due to security vulnerabilities and CircleCI's Ruby version. We need to either:

- Use Slather again, but find a way to use Ruby > 2.0.0 on CircleCI in a macOS build
- Use another tool to upload coverage data to Coveralls

**Comment by mattyohe** [comment]
Latest versions of ruby are already installed, just have to choose them with .ruby-version as seen here: https://circleci.com/docs/2.0/testing-ios/#custom-ruby-versions
